### ISSUE TITLE
Instructions on installation page have a mistake.

### ISSUE THREAD

**Issue by tfabris** [al-caughey/YAMon-v4#4]
On this web page:
- https://usage-monitoring.com/v4Install+Validate.php

On that page, after copying install.sh to /opt/, there is a mistake in the instructions. It says:
```
give 'install.sh' execute permission
chmod +x /opt/
```
This gives the folder execute permission but it did not give the install.sh file execute permissions in my case. To avoid a "permission denied" error message, I had to also issue this command as well:
```
chmod +x /opt/install.sh
```

There is also an omission of instructions on this web site, regarding how to format and mount the necessary USB stick. Like me, many YaMon first-time users will also be installing a USB stick into their DD-WRT-enabled router for the first time. I was able to glean the necessary information via a lot of googling and a lot of trial and error, but it took me far too long. It would be nice if the "USB" help pages on the on the usage-monitoring.com site could give (or link to) more information about how this is done. For example, on my installation of DD-WRT, I had to do the following:

```
This section is needed for USB stick plugged into router, for YaMon
third-party tool. USB stick must have been pre-formatted with EXT4 file
system, I used my Synology NAS to format it as EXT4 (Control Panel, External
Devices).

In the DD-WRT web user interface, navigate to "Services", "USB"

  Core USB Support                   Enable
  USB Storage Support                Enable
  Automatic Drive Mount              Enable
  Mount this Partition to /opt       (Leave blank at first)

      AFTER SAVE/APPLY, REBOOT THE ROUTER THEN COME BACK TO THIS PAGE

After rebooting the router, you should theoretically see the USB drive now as
one of the items under "Disk Info" on this page, for instance you might see
something like this:

    UUID FF28F93B-FEEE-4E2A-8200-B293B6805FF9 (DCE, v4) 
    Volume size 57.28 GiB (61500284928 bytes, 15014718 blocks of 4 KiB) 
    /dev/sda1 mounted to /tmp/mnt/sda1

Copy that UUID into this section of this screen:

  Mount this Partition to /opt       (UUID number from the disk info)

      SAVE/APPLY, REBOOT THE ROUTER ONCE MORE TO MAKE IT AUTO MOUNT.

After rebooting the router, you should now see the USB drive mounted to /opt/
like this:

    UUID FF28F93B-FEEE-4E2A-8200-B293B6805FF9 (DCE, v4) 
    Volume size 57.28 GiB (61500284928 bytes, 15014718 blocks of 4 KiB) 
    /dev/sda1 mounted to /opt
```

**Comment by al-caughey** [comment]
Tony - Yes and yes.
See https://usage-monitoring.com/v4Install+Validate.php and http://usage-monitoring.com/help/?t=dd-wrt-usb

**Comment by tfabris** [comment]
Fantastic! Thanks!
